#!/usr/bin/env bash

set -ex

git checkout master
git checkout -B gh-pages

npm run build
git rm -rf src/*
git rm -rf $(ls | grep -f <(git ls-files))
git commit -m 'Remove project files'

mv build/* .
git add .
git commit -m 'Add build files'

git push -f origin gh-pages

git checkout master

echo "Published latest version to gh-pages"
